# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d31aa1bb22589ca8cc422c3f6900fbdb5c02b3af7af5e5e209a73b936fe7c1ad22705a66a3d0c35a0c853e9915a4fb0df85984ba6144e6ddf2db051555128485

test:
  secret_key_base: 1cfe3056dea07d57cf8c3a4c01513867f0c8be243d1d07753c4d2da3a2dfd347246662cff6951c28cdcab41f413463d2f41bd2d3d27aba58276af53f2916ec7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
